apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
  namespace: dragonfly-operator-system
spec:
  interval: 10m
  chart:
    spec:
      chart: dragonfly-operator
      version: "1.3.1"
      sourceRef:
        kind: HelmRepository
        name: dragonfly-operator-oci
        namespace: dragonfly-operator-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3