apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dragonfly-operator
  namespace: dragonfly-operator-system
spec:
  interval: 1h
  url: https://www.dragonflydb.io/helm-charts