apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: dragonfly-operator
  namespace: dragonfly-operator-system
spec:
  interval: 1h
  url: oci://ghcr.io/dragonflydb/dragonfly-operator/helm
  ref:
    tag: v1.3.1